steps:
  - wait

  - label: ":darwin: Anka - Ensure Mojave Template Dependency Tag/Layer Exists"
    command:
      - "git clone git@github.com:EOSIO/mac-anka-fleet.git -b support-for-new-cicd"
    #   - "cd mac-anka-fleet && . ./ensure_tag.bash -u 12 -r 25G -a '-n'"
    # env:
    #   REPO: ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}
    #   REPO_COMMIT: $BUILDKITE_COMMIT
    #   TEMPLATE: "10.14.4_6C_14G_40G"
    #   TEMPLATE_TAG: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
    #   TAG_COMMANDS: "git clone https://github.com/$(echo ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} | awk -F'github.com:' '{print $2}') eos && cd eos && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive && ./.cicd/anka/macos-10.14.sh && cd .. && rm -rf eos"
    #   PROJECT_TAG: "eos-macos-10.14-cf94bae63f2ceab7ef0e99a48a6f4c6ba464b38a"
    agents:
      queue: "mac-anka-templater-fleet"
    timeout: ${TIMEOUT:-320}

  # - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "amazon_linux-2"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.6 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "centos-7.6"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "git clone $BUILDKITE_REPO eos && cd eos && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos && ./.cicd/build.sh"
      - "cd eos && tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      PINNED: "true"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::eos-macos-10.14-cf94bae63f2ceab7ef0e99a48a6f4c6ba464b38a"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: ${SKIP_MOJAVE}
    
  - wait

  - label: ":aws: Amazon_Linux 2 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/parallel-tests.sh"
    env:
      IMAGE_TAG: "amazon_linux-2"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_UNIT_TESTS}

  - label: ":centos: CentOS 7.6 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.6 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/parallel-tests.sh"
    env: 
      IMAGE_TAG: "centos-7.6"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 16.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/parallel-tests.sh"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/parallel-tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_UNIT_TESTS}

  - label: ":darwin: macOS 10.14 - Unit Tests"
    command:
      - "git clone $BUILDKITE_REPO eos && cd eos && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eos && ./.cicd/parallel-tests.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::eos-macos-10.14-cf94bae63f2ceab7ef0e99a48a6f4c6ba464b38a"
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-node-fleet"
    skip: ${SKIP_MOJAVE}${SKIP_UNIT_TESTS}

  - label: ":pipeline: Generate Serial Test Steps"  
    command: "./.cicd/generate-serial-tests.sh | buildkite-agent pipeline upload"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_GENERATE_SERIAL_TESTS

  - label: ":aws: Amazon_Linux 2 - Long-Running Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/long-running-tests.sh"
    env:
      IMAGE_TAG: "amazon_linux-2"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_LONG_RUNNING_TESTS:-true}

  - label: ":centos: CentOS 7.6 - Long-Running Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.6 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/long-running-tests.sh"
    env: 
      IMAGE_TAG: "centos-7.6"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_LONG_RUNNING_TESTS:-true}

  - label: ":ubuntu: Ubuntu 16.04 - Long-Running Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/long-running-tests.sh"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_LONG_RUNNING_TESTS:-true}

  - label: ":ubuntu: Ubuntu 18.04 - Long-Running Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/long-running-tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LONG_RUNNING_TESTS:-true}

  - label: ":darwin: macOS 10.14 - Long-Running Tests"
    command:
      - "git clone $BUILDKITE_REPO eos && cd eos && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eos && ./.cicd/long-running-tests.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::eos-macos-10.14-cf94bae63f2ceab7ef0e99a48a6f4c6ba464b38a"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: ${SKIP_MOJAVE}${SKIP_LONG_RUNNING_TESTS:-true}

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Test Metrics"
    command: |
      echo '+++ :compression: Extracting Test Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Contract Builder"
    command:
      - "./.cicd/installation-build.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_CONTRACT_BUILDER}

  - label: ":centos: CentOS 7.6 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.6 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      IMAGE_TAG: "centos-7.6"
      BUILDKITE_AGENT_ACCESS_TOKEN:
      OS: "el7" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 16.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      IMAGE_TAG: "ubuntu-16.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
      OS: "ubuntu-16.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 18.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      BUILDKITE_AGENT_ACCESS_TOKEN:
      OS: "ubuntu-18.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_PACKAGE_BUILDER}

  - label: ":darwin: Mojave - Package Builder"
    command:
      - "git clone $BUILDKITE_REPO eos && cd eos && git checkout $BUILDKITE_COMMIT"
      - "cd eos && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eos && ./.cicd/package.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::eos-macos-10.14-cf94bae63f2ceab7ef0e99a48a6f4c6ba464b38a"
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: 10
    skip: ${SKIP_MOJAVE}${SKIP_PACKAGE_BUILDER}

  - label: ":git: Git Submodule Regression Check"
    command:
      - "./.cicd/submodule-regression-checker.sh"
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: 5