steps:
  - wait

  - label: ":pipeline: Generate Pipeline Steps"  
    command: "./.cicd/generate-pipeline.sh | buildkite-agent pipeline upload"
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: ${TIMEOUT:-10}
  
  - wait

  - label: ":git: Git Submodule Regression Check"
    command:
      - "./.cicd/submodule-regression-check.sh"
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: ${TIMEOUT:-5}