env:
  BUILD_TIMEOUT: 120
  TEST_TIMEOUT: 60
  TIMEOUT: 120
  VERBOSE: true

steps:
  - wait

  - label: ":webhook: Trigger Travis CI Build"
    command: |
      . ./.cicd/trigger-travis.sh
    agents:
      queue: "automation-eos-builder-fleet"

  - trigger: "eosio-base-images-beta"
    label: ":docker: Ensure base images exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eosio-amazonlinux-2-5e20c60cfce1471deb7d970bd55a35240c583252"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.6 - Build"
    command:
      - ""
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eosio-centos-7.6-6d1d8821e92fc3e6ebfb61a40d6778b8934d008e"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eosio-ubuntu-16.04-b59dcc9c547a0e17ea1dfcc5ba2bbfc74ed5df11"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eosio-ubuntu-18.04-a269bf2e944de92084f25b95a2309bce3828a9f9"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "brew install git graphviz libtool gmp llvm@4 pkgconfig python python@2 doxygen libusb openssl boost@1.70 cmake"
      - "git clone $BUILDKITE_REPO eos && cd eos && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos && mkdir build && cd build && cmake .. && make -j$(getconf _NPROCESSORS_ONLN)"
      - "cd eos/build && ctest -j$(getconf _NPROCESSORS_ONLN) -LE _tests --output-on-failure -T Test"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_MOJAVE
    