steps:
  - label: ":spiral_note_pad: Generate Report"
    command: |
        echo "--- :hammer: Ensuring lcov is installed" && apt-get install -y lcov && \
        echo "--- :hammer: Building" && \
        cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-4.0 -DCMAKE_C_COMPILER=clang-4.0 -DBOOST_ROOT="${BOOST_ROOT}" -DOPENSSL_ROOT_DIR="${OPENSSL_ROOT_DIR}" -DBUILD_MONGO_DB_PLUGIN=true -DENABLE_COVERAGE_TESTING=true -DBUILD_DOXYGEN=false && \
        ninja && \
        echo "--- :spiral_note_pad: Generating Code Coverage Report" && \
        ninja EOSIO_ut_coverage && \
        echo "--- :arrow_up: Publishing Code Coverage Report" && \
        buildkite-agent artifact upload "EOSIO_ut_coverage/**/*" s3://eos-coverage/$BUILDKITE_JOB_ID && \
        echo "+++ View Report" && \
        printf "\033]1339;url=https://eos-coverage.s3-us-west-2.amazonaws.com/$BUILDKITE_JOB_ID/EOSIO_ut_coverage/index.html;content=View Full Coverage Report\a\n"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.0.1:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-1"
        workdir: /data/job
        environment:
          - LCOV_PATH=/usr/bin/lcov
          - BOOST_ROOT=/root/opt/boost
          - OPENSSL_ROOT_DIR=/usr/include/openssl
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/opt/mongodb/bin:~/opt/llvm/bin/
    timeout: 60
