steps:
  - command: |
      echo "--- Creating symbolic link to job directory :file_folder:" && \
      sleep 5 && ln -s "$(pwd)" /data/job && cd /data/job && \
      echo "+++ Building :hammer:" && \
      echo 1 | ./eosio_build.sh -o Debug && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    label: ":darwin: Mojave Build"
    agents:
      - "role=builder-v2-1"
      - "os=mojave"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":ubuntu: 16.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-1"
        workdir: /data/job
    timeout: 60
    
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":ubuntu: 18.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":fedora: 27 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:fedora27_2-1"
        workdir: /data/job
    timeout: 60
 
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":centos: 7 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":aws: 1 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux1_2-1"
        workdir: /data/job
    timeout: 60

    - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh -o Debug && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":aws: 2 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-1"
        workdir: /data/job
    timeout: 60

  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":darwin: Mojave Tests"
    agents:
      - "role=builder-v2-1"
      - "os=mojave"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60
    
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 16.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: 16.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-1"
        workdir: /data/job
    timeout: 60
  
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: 18.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":fedora: 27 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":fedora: 27 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:fedora27_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: 7 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":centos: 7 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: 1 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":aws: 1 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux1_2-1"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: 2 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":aws: 2 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-1"
        workdir: /data/job
    timeout: 60