steps:
  - command: |
      echo "--- Creating symbolic link to job directory :file_folder:" && \
      sleep 5 && ln -s "$(pwd)" /data/job && cd /data/job && \
      echo "+++ Building :hammer:" && \
      echo 1 | ./eosio_build.sh && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    label: ":darwin: Build"
    agents:
      - "role=macos-builder"
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":ubuntu: Build"
    agents:
      - "role=linux-builder"
    artifact_paths: "build.tar.gz"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60
    
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":ubuntu: 18.04 Build"
    agents:
      - "role=linux-builder"
    artifact_paths: "build.tar.gz"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":fedora: Build"
    agents:
      - "role=linux-builder"
    artifact_paths: "build.tar.gz"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    timeout: 60
 
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":centos: Build"
    agents:
      - "role=linux-builder"
    artifact_paths: "build.tar.gz"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./eosio_build.sh && \
        echo "--- :compression: Compressing build directory" && \
        tar -pczf build.tar.gz build/
    label: ":aws: Build"
    agents:
      - "role=linux-builder"
    artifact_paths: "build.tar.gz"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:amazonlinux"
        workdir: /data/job
    timeout: 60

  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":darwin: Tests"
    agents:
      - "role=macos-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":darwin: NP Tests"
    agents:
      - "role=macos-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    timeout: 60
    
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":ubuntu: Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":ubuntu: NP Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60
  
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":ubuntu: 18.04 Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":ubuntu: 18.04 NP Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":fedora: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":fedora: Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":fedora: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":fedora: NP Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":centos: Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":centos: NP Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    label: ":aws: Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:amazonlinux"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Build" && \
        tar -zxf build.tar.gz && \
        echo "--- :m: Starting MongoDB" && \
        $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
        echo "+++ :microscope: Running tests" && \
        cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    label: ":aws: NP Tests"
    agents:
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:amazonlinux"
        workdir: /data/job
    timeout: 60

  - wait

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build/packages && bash generate_package.sh brew
    label: ":darwin: High Sierra Package Builder"
    agents:
      - "role=macos-builder"
      - "os=high-sierra"
    artifact_paths:
      - "build/packages/*.tar.gz"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        ln -s "$(pwd)" /data/job && cd /data/job/build/packages && bash generate_package.sh brew
    label: ":darwin: Mojave Package Builder"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths:
      - "build/packages/*.tar.gz"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        cd /data/job/build/packages && bash generate_package.sh deb
    label: ":ubuntu: Package builder"
    agents:
      - "role=linux-builder"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    env:
      OS: "ubuntu-16.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        cd /data/job/build/packages && bash generate_package.sh deb
    label: ":ubuntu: 18.04 Package builder"
    agents:
      - "role=linux-builder"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    env:
      OS: "ubuntu-18.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":fedora: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        yum install -y rpm-build && \
        mkdir -p /root/rpmbuild/BUILD && \
        mkdir -p /root/rpmbuild/BUILDROOT && \
        mkdir -p /root/rpmbuild/RPMS && \
        mkdir -p /root/rpmbuild/SOURCES && \
        mkdir -p /root/rpmbuild/SPECS && \
        mkdir -p /root/rpmbuild/SRPMS && \
        cd /data/job/build/packages && bash generate_package.sh rpm
    label: ":fedora: Package builder"
    agents:
      - "role=linux-builder"
    artifact_paths:
      - "build/packages/x86_64/*.rpm"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    env:
      OS: "fedora"
      PKGTYPE: "rpm"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Starting package build" && \
        yum install -y rpm-build && \
        mkdir -p /root/rpmbuild/BUILD && \
        mkdir -p /root/rpmbuild/BUILDROOT && \
        mkdir -p /root/rpmbuild/RPMS && \
        mkdir -p /root/rpmbuild/SOURCES && \
        mkdir -p /root/rpmbuild/SPECS && \
        mkdir -p /root/rpmbuild/SRPMS && \
        cd /data/job/build/packages && bash generate_package.sh rpm
    label: ":centos: Package builder"
    agents:
      - "role=linux-builder"
    artifact_paths:
      - "build/packages/x86_64/*.rpm"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    env:
      OS: "centos"
      PKGTYPE: "rpm"
    timeout: 60
