steps:
  - command: | # Ubuntu 16.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 16.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - command: | # Ubuntu 18.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 18.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - wait

  # Ubuntu 16.04 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":ubuntu: Ubuntu 16.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Ubuntu 18.04 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":ubuntu: Ubuntu 18.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - wait:
    continue_on_failure: true

  - command: |
        cd scripts/metrics
        node --max-old-space-size=4096 test-metrics.js
    label: ":bar_chart: Test Metrics"
    agents:
      queue: "automation-apps-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - command: | # Ubuntu 16.04 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /data/job/build/packages
        bash generate_package.sh deb
    label: ":ubuntu: Ubuntu 16.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-16.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: | # Ubuntu 18.04 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /data/job/build/packages
        bash generate_package.sh deb
    label: ":ubuntu: Ubuntu 18.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-18.04"
      PKGTYPE: "deb"
    timeout: 60