steps:
  - command: | # macOS Mojave Build
      echo "--- Creating symbolic link to job directory :file_folder:"
      sleep 5
      ln -s "$(pwd)" /data/job
      cd /data/job
      echo "+++ Building :hammer:"
      ./scripts/eosio_build.sh -y -P -m
      echo "--- Compressing build directory :compression:"
      tar -pczf build.tar.gz build
      if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":darwin: Mojave Build"
    agents:
      - "role=builder-v2-2"
      - "os=mojave"
    artifact_paths: "build.tar.gz"
    timeout: 120

  - command: | # Amazon Linux 2 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":aws: Amazon Linux 2 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - command: | # CentOS 7 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":centos: CentOS 7 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - command: | # Ubuntu 16.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 16.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - command: | # Ubuntu 18.04 Build
        echo "+++ :hammer: Building"
        ./scripts/eosio_build.sh -y -P -m
        echo "--- :compression: Compressing build directory"
        tar -pczf build.tar.gz build
        if [[ ! -f build.tar.gz ]]; then echo 'ERROR: No build.tar.gz artifact found!' && exit 1; fi
    label: ":ubuntu: Ubuntu 18.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - wait

  # Amazon Linux 2 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Amazon Linux 2 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":aws: Amazon Linux 2 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Amazon Linux 2 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/serial-test.sh
    label: ":aws: Amazon Linux 2 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # centOS 7 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: CentOS 7 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":centos: CentOS 7 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: CentOS 7 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/serial-test.sh
    label: ":centos: CentOS 7 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Ubuntu 16.04 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":ubuntu: Ubuntu 16.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/serial-test.sh
    label: ":ubuntu: Ubuntu 16.04 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Ubuntu 18.04 Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/parallel-test.sh
    label: ":ubuntu: Ubuntu 18.04 Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        echo "+++ :microscope: Running Tests"
        ./scripts/serial-test.sh
    label: ":ubuntu: Ubuntu 18.04 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Mojave Tests
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build"
        echo "+++ :microscope: Running Tests"
        ln -s "$(pwd)" /data/job
        ./scripts/parallel-test.sh
    label: ":darwin: Mojave Tests"
    agents:
      - "role=tester-v2-2"
      - "os=mojave"
    timeout: 60
  - command: |
        echo "--- :arrow_down: Downloading Build Directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build"
        echo "+++ :microscope: Running Tests"
        ln -s "$(pwd)" /data/job
        ./scripts/serial-test.sh
    label: ":darwin: Mojave NP Tests"
    agents:
      - "role=tester-v2-1"
      - "os=mojave"
    timeout: 60

  - wait:
    continue_on_failure: true

  - command: |
        cd scripts/metrics
        node --max-old-space-size=4096 test-metrics.js
    label: ":bar_chart: Test Metrics"
    agents:
      queue: "automation-apps-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - command: | # CentOS 7 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: CentOS 7 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        yum install -y rpm-build
        mkdir -p /root/rpmbuild/BUILD
        mkdir -p /root/rpmbuild/BUILDROOT
        mkdir -p /root/rpmbuild/RPMS
        mkdir -p /root/rpmbuild/SOURCES
        mkdir -p /root/rpmbuild/SPECS
        mkdir -p /root/rpmbuild/SRPMS
        cd /data/job/build/packages
        bash generate_package.sh rpm
    label: ":centos: CentOS 7 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/*.rpm"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_2-3"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "el7"
      PKGTYPE: "rpm"
    timeout: 60

  - command: | # Ubuntu 16.04 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /data/job/build/packages
        bash generate_package.sh deb
    label: ":ubuntu: Ubuntu 16.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_2-3"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-16.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: | # Ubuntu 18.04 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /data/job/build/packages
        bash generate_package.sh deb
    label: ":ubuntu: Ubuntu 18.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/*.deb"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v2.1.0:
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_2-3"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-18.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: | # macOS Mojave Package Builder
        echo "--- :arrow_down: Downloading build directory"
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Mojave Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        ln -s "$(pwd)" /data/job
        cd /data/job/build/packages
        bash generate_package.sh brew
    label: ":darwin: Mojave Package Builder"
    agents:
      - "role=builder-v2-2"
      - "os=mojave"
    artifact_paths:
      - "build/packages/*.tar.gz"
      - "build/packages/*.rb"
    timeout: 60

  - wait

  - command: | # Brew Updater
        echo "--- :arrow_down: Downloading brew files"
        buildkite-agent artifact download "build/packages/eosio.rb" . --step ":darwin: Mojave Package Builder"
    label: ":darwin: Brew Updater"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/eosio.rb"
    timeout: 5

  - command: | # Git Submodule Regression Check
        echo "+++ :microscope: Running git submodule regression check" && \
        ./scripts/submodule_check.sh
    label: "Git Submodule Regression Check"
    agents:
      queue: "automation-large-builder-fleet"
    timeout: 5