steps:
  - label: ":docker: create base image"
    command: ".buildkite/steps/build-builder.sh"
    timeout: 60

  - wait

  - label: ":floppy_disk: upload base image"
    command: ".buildkite/steps/publish-builder.sh"
    branches: "master ci-*"

  - wait

  - label: ":docker: build docker image"
    command: ".buildkite/steps/build-image.sh"
    timeout: 60

  - wait

  - label: ":floppy_disk: upload image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master ci-*"

  - wait

  - label: "fake test %n"
    command: "echo \"TODO Testing... done\""
    parallelism: 10

  - wait

  - label: ":slack:"
    command: ".buildkite/steps/slack.sh \"Pipeline complete successfully\""
