steps:
  - command:
    - "cd Docker/builder"
    - "docker build -t cyberway/builder ."
    label: ":docker: create base image"
    timeout: 60

  - wait

  - command:
    - "docker images"
    - "docker login -u=$DHUBU -p=$DHUBP"
    - "docker push cyberway/builder"
    label: ":floppy_disk: upload base image"
    branches: "master"

  - wait

  - command:
    - "imagetag=\"${BUILDKITE_BRANCH}\""
    - "cd Docker"
    - "docker build -t cyberway/cyberway:$imagetag --build-arg branch=$BUILDKITE_BRANCH ."
    label: ":docker: build docker image"
    timeout: 60

  - wait

  - command:
    - "docker images"
    - "imagetag=\"${BUILDKITE_BRANCH}\""
    - "docker login -u=$DHUBU -p=$DHUBP"
    - "docker push cyberway/cyberway:$imagetag"
    label: ":floppy_disk: upload image"
    branches: "master"

  - wait

  - command:
    - "echo \"TODO Testing... done\""
    label: "fake test %n"
    parallelism: 10

  - wait

  - command:
    - "curl -X POST -H 'Content-type: application/json' --data '{"text":":thumbsup: Cyberway: pipeline complete successfully"}' ${WEBHOOK}"
    label: ":slack:"