# set environment variables (EOSIO_ROOT and CMAKE_FRAMEWORK_PATH are autogenerated)
RUN PATH=/usr/local/eosio/bin:$(echo "/usr/opt/eosio.cdt/$(ls /usr/opt/eosio.cdt)/bin"):$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib