#ifndef VM_EXCEPTIONS_H_
#define VM_EXCEPTIONS_H_

enum exception_type {
    enum_exception,
    enum_timeout_exception,
    enum_file_not_found_exception,
    enum_parse_error_exception,
    enum_invalid_arg_exception,
    enum_key_not_found_exception,
    enum_bad_cast_exception,
    enum_out_of_range_exception,
    enum_invalid_operation_exception,
    enum_unknown_host_exception,
    enum_canceled_exception,
    enum_assert_exception,
    enum_eof_exception,
    enum_null_optional,
    enum_udt_exception,
    enum_aes_exception,
    enum_overflow_exception,
    enum_underflow_exception,
    enum_divide_by_zero_exception,

    enum_chain_exception,
    enum_chain_type_exception,
    enum_name_type_exception,
    enum_public_key_type_exception,
    enum_private_key_type_exception,
    enum_authority_type_exception,
    enum_action_type_exception,
    enum_transaction_type_exception,
    enum_abi_type_exception,
    enum_block_id_type_exception,
    enum_transaction_id_type_exception,
    enum_packed_transaction_type_exception,
    enum_asset_type_exception,
    enum_chain_id_type_exception,
    enum_fixed_key_type_exception,
    enum_symbol_type_exception,
    enum_fork_database_exception,
    enum_fork_db_block_not_found,
    enum_block_validate_exception,
    enum_unlinkable_block_exception,
    enum_block_tx_output_exception,
    enum_block_concurrency_exception,
    enum_block_lock_exception,
    enum_block_resource_exhausted,
    enum_block_too_old_exception,
    enum_block_from_the_future,
    enum_wrong_signing_key,
    enum_wrong_producer,
    enum_transaction_exception,
    enum_tx_decompression_error,
    enum_tx_no_action,
    enum_tx_no_auths,
    enum_cfa_irrelevant_auth,
    enum_expired_tx_exception,
    enum_tx_exp_too_far_exception,
    enum_invalid_ref_block_exception,
    enum_tx_duplicate,
    enum_deferred_tx_duplicate,
    enum_cfa_inside_generated_tx,
    enum_tx_not_found,
    enum_too_many_tx_at_once,
    enum_tx_too_big,
    enum_unknown_transaction_compression,
    enum_action_validate_exception,
    enum_account_name_exists_exception,
    enum_invalid_action_args_exception,
    enum_eosio_assert_message_exception,
    enum_eosio_assert_code_exception,
    enum_action_not_found_exception,
    enum_action_data_and_struct_mismatch,
    enum_unaccessible_api,
    enum_abort_called,
    enum_inline_action_too_big,
    enum_database_exception,
    enum_permission_query_exception,
    enum_account_query_exception,
    enum_contract_table_query_exception,
    enum_contract_query_exception,
    enum_guard_exception,
    enum_database_guard_exception,
    enum_reversible_guard_exception,
    enum_wasm_exception,
    enum_page_memory_error,
    enum_wasm_execution_error,
    enum_wasm_serialization_error,
    enum_overlapping_memory_error,
    enum_binaryen_exception,
    enum_resource_exhausted_exception,
    enum_ram_usage_exceeded,
    enum_tx_net_usage_exceeded,
    enum_block_net_usage_exceeded,
    enum_tx_cpu_usage_exceeded,
    enum_block_cpu_usage_exceeded,
    enum_deadline_exception,
    enum_greylist_net_usage_exceeded,
    enum_greylist_cpu_usage_exceeded,
    enum_leeway_deadline_exception,
    enum_authorization_exception,
    enum_tx_duplicate_sig,
    enum_tx_irrelevant_sig,
    enum_unsatisfied_authorization,
    enum_missing_auth_exception,
    enum_irrelevant_auth_exception,
    enum_insufficient_delay_exception,
    enum_invalid_permission,
    enum_unlinkable_min_permission_action,
    enum_invalid_parent_permission,
    enum_misc_exception,
    enum_rate_limiting_state_inconsistent,
    enum_unknown_block_exception,
    enum_unknown_transaction_exception,
    enum_fixed_reversible_db_exception,
    enum_extract_genesis_state_exception,
    enum_subjective_block_production_exception,
    enum_multiple_voter_info,
    enum_unsupported_feature,
    enum_node_management_success,
    enum_plugin_exception,
    enum_missing_chain_api_plugin_exception,
    enum_missing_wallet_api_plugin_exception,
    enum_missing_history_api_plugin_exception,
    enum_missing_net_api_plugin_exception,
    enum_missing_chain_plugin_exception,
    enum_plugin_config_exception,
    enum_wallet_exception,
    enum_wallet_exist_exception,
    enum_wallet_nonexistent_exception,
    enum_wallet_locked_exception,
    enum_wallet_missing_pub_key_exception,
    enum_wallet_invalid_password_exception,
    enum_wallet_not_available_exception,
    enum_wallet_unlocked_exception,
    enum_key_exist_exception,
    enum_key_nonexistent_exception,
    enum_unsupported_key_type_exception,
    enum_invalid_lock_timeout_exception,
    enum_secure_enclave_exception,
    enum_whitelist_blacklist_exception,
    enum_actor_whitelist_exception,
    enum_actor_blacklist_exception,
    enum_contract_whitelist_exception,
    enum_contract_blacklist_exception,
    enum_action_blacklist_exception,
    enum_key_blacklist_exception,
    enum_controller_emit_signal_exception,
    enum_checkpoint_exception,
    enum_abi_exception,
    enum_abi_not_found_exception,
    enum_wasm_file_not_found,
    enum_invalid_ricardian_clause_exception,
    enum_invalid_ricardian_action_exception,
    enum_invalid_type_inside_abi,
    enum_duplicate_abi_type_def_exception,
    enum_duplicate_abi_struct_def_exception,
    enum_duplicate_abi_action_def_exception,
    enum_duplicate_abi_table_def_exception,
    enum_duplicate_abi_err_msg_def_exception,
    enum_abi_serialization_deadline_exception,
    enum_abi_recursion_depth_exception,
    enum_abi_circular_def_exception,
    enum_unpack_exception,
    enum_pack_exception,
    enum_duplicate_abi_variant_def_exception,
    enum_unsupported_abi_version_exception,
    enum_contract_exception,
    enum_invalid_table_payer,
    enum_table_access_violation,
    enum_invalid_table_iterator,
    enum_table_not_in_cache,
    enum_table_operation_not_permitted,
    enum_invalid_contract_vm_type,
    enum_invalid_contract_vm_version,
    enum_set_exact_code,
    enum_wast_file_not_found,
    enum_abi_file_not_found,
    enum_producer_exception,
    enum_producer_priv_key_not_found,
    enum_missing_pending_block_state,
    enum_producer_double_confirm,
    enum_producer_schedule_exception,
    enum_producer_not_in_schedule,
    enum_reversible_blocks_exception,
    enum_invalid_reversible_blocks_dir,
    enum_reversible_blocks_backup_dir_exist,
    enum_gap_in_reversible_blocks_db,
    enum_block_log_exception,
    enum_block_log_unsupported_version,
    enum_block_log_append_fail,
    enum_block_log_not_found,
    enum_block_log_backup_dir_exist,
    enum_http_exception,
    enum_invalid_http_client_root_cert,
    enum_invalid_http_response,
    enum_resolved_to_multiple_ports,
    enum_fail_to_resolve_host,
    enum_http_request_fail,
    enum_invalid_http_request,
    enum_resource_limit_exception,
    enum_mongo_db_exception,
    enum_mongo_db_insert_fail,
    enum_mongo_db_update_fail,
    enum_contract_api_exception,
    enum_crypto_api_exception,
    enum_db_api_exception,
    enum_arithmetic_exception,
    enum_abi_generation_exception,

    enum_snapshot_exception,
    enum_snapshot_validation_exception,
    enum_snapshot_directory_not_found_exception,
    enum_snapshot_exists_exception,
    enum_explained_exception,
    enum_localized_exception,
};

extern "C" void vm_api_throw_exception(int type, const char* fmt, ...);

#undef EOS_THROW
#undef EOS_ASSERT
#undef FC_THROW_EXCEPTION

#define FC_THROW_EXCEPTION( exc_type, FORMAT, ... ) \
  FC_MULTILINE_MACRO_BEGIN \
   vm_api_throw_exception( enum_##exc_type, FC_LOG_MESSAGE( error, FORMAT, __VA_ARGS__ ).get_message().c_str() ); \
  FC_MULTILINE_MACRO_END


#define EOS_THROW( exc_type, FORMAT, ... ) \
   vm_api_throw_exception( enum_##exc_type, FC_LOG_MESSAGE( error, FORMAT, __VA_ARGS__ ).get_message().c_str() ); \


#define EOS_ASSERT( expr, exc_type, FORMAT, ... )                \
   FC_MULTILINE_MACRO_BEGIN                                      \
   if( !(expr) ) {                                               \
      EOS_THROW(exc_type, FORMAT, __VA_ARGS__);                  \
   }                                                             \
   FC_MULTILINE_MACRO_END


#endif
