(module
  (type $T (func (param) (result i32)))
  (type $U (func (param) (result i32)))
  (table anyfunc (elem $t1 $t2 $t3 $u1 $u2 $t1 $t3))

  (func $t1 (type $T) (i32.const 1))
  (func $t2 (type $T) (i32.const 2))
  (func $t3 (type $T) (i32.const 3))
  (func $u1 (type $U) (i32.const 4))
  (func $u2 (type $U) (i32.const 5))

  (func $callt (param $i i32) (result i32)
    (call_indirect $T (get_local $i))
  )

  (func $callu (param $i i32) (result i32)
    (call_indirect $U (get_local $i))
  )

  (func (export "main")
    (drop (call $callt (i32.const 0)))
    (drop (call $callt (i32.const 1)))
    (drop (call $callt (i32.const 2)))
    (drop (call $callt (i32.const 3)))
    (drop (call $callt (i32.const 4)))
    (drop (call $callt (i32.const 5)))
    (drop (call $callt (i32.const 6)))
    (drop (call $callu (i32.const 0)))
    (drop (call $callu (i32.const 1)))
    (drop (call $callu (i32.const 2)))
    (drop (call $callu (i32.const 3)))
    (drop (call $callu (i32.const 4)))
    (drop (call $callu (i32.const 5)))
    (drop (call $callu (i32.const 6)))
    )
)
